services:
  axonserver:
    container_name: axonserver
    image: axoniq/axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
    volumes:
      - axonserver-data:/axonserver/data
      - axonserver-events:/axonserver/eventdata
      - axonserver-config:/axonserver/config
    environment:
      #- AXONIQ_AXONSERVER_PORT=8024
      - AXONIQ_AXONSERVER_NAME=DJ Axon Server
      - AXONIQ_AXONSERVER_HOSTNAME=localhost
      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=true



volumes:
  axonserver-data:
  axonserver-events:
  axonserver-config: